apiVersion: installer.devtron.ai/v1alpha1
kind: Installer
metadata:
  name: installer-devtron
  namespace: devtroncd
spec:
  url: https://raw.githubusercontent.com/akshatsinha007/devtron/v3.0.0/manifests/installation-script
