name: OpenAPI Lint and Build Documentation

on:
  pull_request:
    paths:
      - 'specs/swagger/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
          
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
        
      - name: Lint OpenAPI specification
        run: |
          cd specs/swagger
          echo "Linting OpenAPI specification..."
          redocly lint openapi.yaml --skip-rule=warning
          echo "Linting passed! No critical errors found."
        
      - name: Build OpenAPI documentation
        run: |
          cd specs/swagger
          echo "🔨 Building OpenAPI documentation..."
          redocly build-docs openapi.yaml --output=openapi.html
          echo "Documentation built successfully!"
          
      - name: Commit and push updated documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add specs/swagger/openapi.html
          
          if git diff --staged --quiet; then
            echo "📝 No changes to commit"
          else
            git commit -m "Update OpenAPI documentation [skip ci]"
            echo "📝 Documentation updated and committed"
            git push origin HEAD:${{ github.head_ref }}
            echo "📤 Changes pushed to PR branch"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SYSTEMSDT_TOKEN }}
